"""Shared fixtures.

Every builder returns plain JSON-shaped data, so a test can corrupt exactly one
field and prove that the corruption — and nothing else — is what refuses.
"""

from __future__ import annotations

import hashlib
import json
import shutil
from collections.abc import Callable, Iterator
from pathlib import Path
from typing import Any

import pytest

from latent_compass.benchmark import (
    BenchmarkSpec,
    CorpusManifest,
    load_benchmark_spec,
    load_corpus_manifest,
)
from latent_compass.decision_memory import (
    DecisionMemoryStore,
    StrategicDecisionRecord,
    admit_strategic_decision,
)
from latent_compass.decision_reconciliation import ReconciliationJournal
from latent_compass.episode import AgentFamily
from latent_compass.ledger import LedgerStore
from latent_compass.protocol import (
    HoldoutLedger,
    MeasurementSet,
    Preregistration,
    Verdict,
    evaluate,
    load_measurement_set,
    load_preregistration,
    recompute_verdict_seal,
)

REPO = Path(__file__).resolve().parents[1]

#: The committed synthetic benchmark corpus. Generated by ``corpus_generator``;
#: see ``corpus/synthetic-v1/PROVENANCE.md``.
BENCHMARK_CORPUS = REPO / "corpus" / "synthetic-v1"

HOST_ID = "host-alpha"
STORE_ID = "store-alpha"
EPOCH = "LC-HOK181-E1-7d1fc727"
FAMILY = "claude"

FIXED_APPEND_TIME = "2026-08-14T12:00:00Z"


@pytest.fixture
def fixed_clock() -> Callable[[], str]:
    """A clock that never moves, so seals depend only on content."""
    return lambda: FIXED_APPEND_TIME


def episode_payload(
    episode_id: str = "ep-00000001",
    *,
    host_id: str = HOST_ID,
    store_id: str = STORE_ID,
    epoch: str = EPOCH,
    agent_family: str = FAMILY,
    **overrides: Any,
) -> dict[str, Any]:
    """A complete, valid episode. Overrides replace top-level keys outright."""
    payload: dict[str, Any] = {
        "schema_version": "1.0.0",
        "episode_id": episode_id,
        "provenance": {
            "host_id": host_id,
            "agent_family": agent_family,
            "store_id": store_id,
            "epoch": epoch,
            "recorded_at": "2026-08-14T10:00:00Z",
            "tool_version": "0.1.0",
        },
        "state": {
            "levels": [
                {"depth": 0, "name": "L6-strategy", "summary_digest": "digest-l6"},
                {"depth": 1, "name": "L5-product-intent", "summary_digest": "digest-l5"},
                {"depth": 2, "name": "L4-invariants", "summary_digest": "digest-l4"},
            ],
            "branch_point": {"node_id": "node-l4-a", "depth": 2, "parent_node_id": "node-l5-a"},
        },
        "candidates": [
            {"direction_id": "dir-alpha", "propensity": 0.6, "prior_uncertainty": 0.2},
            {"direction_id": "dir-beta", "propensity": 0.4, "prior_uncertainty": 0.3},
        ],
        "decision": {
            "advisory": {
                "contract_version": "1.0.0",
                "kind": "DIRECTION",
                "direction_id": "dir-alpha",
                "confidence": 0.7,
                "uncertainty": 0.2,
                "rationale": "higher observed reversibility on the sibling branch",
                "issued_by": "latent_compass",
            },
            "selected_direction_id": "dir-alpha",
        },
        "external_verdict": {
            "judge": "external-judge",
            "verdict": "PASS",
            "observed_at": "2026-08-14T10:05:00Z",
            "evidence_digest": "evidence-digest-1",
        },
        "outcome": {
            "observability": "FULL",
            "observed": True,
            "observed_at": "2026-08-14T11:00:00Z",
            "success": True,
            "violations": 0,
        },
        "economics": {
            "cost": 1.5,
            "information_gain": 0.25,
            "reversibility": 0.9,
            "uncertainty": 0.2,
        },
        "redactions": [],
    }
    payload.update(overrides)
    return payload


def pairwise_projection_payload() -> dict[str, Any]:
    """A complete pre-action sidecar with no selected or post-action fields."""

    def evidence(prefix: str) -> list[dict[str, Any]]:
        dimensions = ("SUCCESS", "VIOLATION", "COST", "INFORMATION", "REVERSIBILITY")
        return [
            {
                "dimension": dimension,
                "availability": "PRESENT",
                "facts": [
                    {
                        "fact_id": f"{prefix}-{index:02d}",
                        "statement": f"Sanitized pre-action fact for {dimension.lower()}",
                        "source_digest": "sha256:" + str(index + 1) * 64,
                    }
                ],
                "reason": None,
            }
            for index, dimension in enumerate(dimensions)
        ]

    return {
        "contract_version": "1.0.0",
        "canonicalization_version": "1.0.0",
        "decision_point_id": "decision-0001",
        "captured_at": "2026-08-16T17:00:00Z",
        "producer_id": "capture-agent-v1",
        "objective_summary": "Choose the safest reversible implementation direction.",
        "context_facts": [
            {
                "fact_id": "context-01",
                "statement": "The public contract must remain backward compatible.",
                "source_digest": "sha256:" + "a" * 64,
            }
        ],
        "constraints": [
            {
                "constraint_id": "constraint-01",
                "kind": "INVARIANT",
                "statement": "The selected direction must not mutate authority.",
                "source_digest": "sha256:" + "b" * 64,
            }
        ],
        "candidates": [
            {
                "direction_id": "direction-alpha",
                "sanitized_summary": "Add a separate immutable pre-action contract.",
                "parameters": [
                    {
                        "name": "max-items",
                        "value": {"kind": "INTEGER", "integer_value": 32},
                    }
                ],
                "applicable_constraint_ids": ["constraint-01"],
                "evidence": evidence("alpha"),
            },
            {
                "direction_id": "direction-beta",
                "sanitized_summary": "Extend a post-action record with optional fields.",
                "parameters": [
                    {
                        "name": "enabled",
                        "value": {"kind": "BOOLEAN", "boolean_value": False},
                    }
                ],
                "applicable_constraint_ids": ["constraint-01"],
                "evidence": evidence("beta"),
            },
        ],
    }


#: The HOK-243 fixture decision. Deadlines sit far enough apart that a test can
#: pick an ``as_of`` before the review, between review and expiry, or after
#: expiry, without any of the three ever colliding.
DECISION_ID = "decision-strategic-0001"
DECISION_CAPTURED_AT = "2026-08-16T09:00:00Z"
DECISION_REVIEW_DUE_AT = "2026-11-16T09:00:00Z"
DECISION_EXPIRES_AT = "2027-08-16T09:00:00Z"
DECISION_AUTHORITY = "operator-alpha"


def strategic_decision_payload(
    decision_id: str = DECISION_ID,
    *,
    revision: int = 1,
    supersedes_revision_seal: str | None = None,
    host_id: str = HOST_ID,
    store_id: str = STORE_ID,
    epoch: str = EPOCH,
    agent_family: str = FAMILY,
    captured_at: str = DECISION_CAPTURED_AT,
    review_due_at: str = DECISION_REVIEW_DUE_AT,
    expires_at: str = DECISION_EXPIRES_AT,
    **overrides: Any,
) -> dict[str, Any]:
    """A complete, admissible strategic decision record.

    The embedded projection is the HOK-234 fixture with its decision point
    rebound to ``decision_id``, so the two identities agree the way the contract
    requires. Overrides replace top-level keys outright.
    """
    projection = pairwise_projection_payload()
    projection["decision_point_id"] = decision_id
    payload: dict[str, Any] = {
        "contract_version": "1.0.0",
        "decision_id": decision_id,
        "revision": revision,
        "supersedes_revision_seal": supersedes_revision_seal,
        "binding": {
            "host_id": host_id,
            "agent_family": agent_family,
            "store_id": store_id,
            "epoch": epoch,
        },
        "captured_at": captured_at,
        "decision_authority": DECISION_AUTHORITY,
        "review_due_at": review_due_at,
        "expires_at": expires_at,
        "impact_class": "STRATEGIC_HIGH_IMPACT",
        "sensitivity": "NON_SENSITIVE",
        "projection": projection,
    }
    payload.update(overrides)
    return payload


@pytest.fixture
def decision_root(tmp_path: Path) -> Path:
    return tmp_path / "decision-root"


@pytest.fixture
def decision_store(
    decision_root: Path, fixed_clock: Callable[[], str]
) -> Iterator[DecisionMemoryStore]:
    """An open decision memory bound to the fixture host, family and epoch."""
    opened = DecisionMemoryStore.create(
        decision_root,
        store_id=STORE_ID,
        host_id=HOST_ID,
        agent_family=AgentFamily.CLAUDE,
        epoch=EPOCH,
        clock=fixed_clock,
    )
    try:
        yield opened
    finally:
        opened.close()


#: The HOK-244 fixture reconciliation. ``RECONCILED_AT`` sits after every
#: observation instant below, so the "an observation cannot postdate its record"
#: rule is satisfied by the default and a test has to break it deliberately.
RECONCILIATION_ID = "reconciliation-0001"
OBSERVED_AT = "2026-08-20T09:00:00Z"
RECONCILED_AT = "2026-08-20T10:00:00Z"
RECONCILED_BY = "observer-alpha"
EXECUTED_DIRECTION_ID = "direction-alpha"
AUTHORITY_REFERENCE = "external-authority-ticket-77"

DIMENSIONS = ("SUCCESS", "VIOLATION", "COST", "INFORMATION", "REVERSIBILITY")

#: One typed value per dimension, so no test relies on every dimension carrying
#: the same scalar kind — a contract that only ever saw booleans would not have
#: been exercised.
_DIMENSION_VALUES: dict[str, dict[str, Any]] = {
    "SUCCESS": {"kind": "BOOLEAN", "boolean_value": True},
    "VIOLATION": {"kind": "INTEGER", "integer_value": 0},
    "COST": {"kind": "FLOAT", "float_value": 1.5},
    "INFORMATION": {"kind": "FLOAT", "float_value": 0.25},
    "REVERSIBILITY": {"kind": "STRING", "string_value": "revert-verified"},
}


def observed_dimension(
    dimension: str,
    *,
    observed_at: str = OBSERVED_AT,
    confidence: float = 0.9,
    **overrides: Any,
) -> dict[str, Any]:
    """One OBSERVED dimension with complete provenance."""
    payload: dict[str, Any] = {
        "dimension": dimension,
        "status": "OBSERVED",
        "statement": f"Post-action observation for {dimension.lower()}.",
        "value": _DIMENSION_VALUES[dimension],
        "provenance": {
            "source_id": f"source-{dimension.lower()}",
            "source_digest": "sha256:" + "c" * 64,
            "observed_at": observed_at,
            "producer": "observer-agent-v1",
            "confidence": confidence,
        },
        "unknown_reason": None,
        "unknown_detail": None,
    }
    payload.update(overrides)
    return payload


def unknown_dimension(dimension: str, reason: str, **overrides: Any) -> dict[str, Any]:
    """One UNKNOWN dimension carrying its named reason and no value."""
    payload: dict[str, Any] = {
        "dimension": dimension,
        "status": "UNKNOWN",
        "statement": None,
        "value": None,
        "provenance": None,
        "unknown_reason": reason,
        "unknown_detail": f"{dimension.lower()} is {reason.lower()} for a stated reason.",
    }
    payload.update(overrides)
    return payload


def observation_set(
    unknowns: dict[str, str] | None = None,
) -> list[dict[str, Any]]:
    """All five dimensions in canonical order; named ones become explicit unknowns."""
    named = unknowns or {}
    return [
        unknown_dimension(dimension, named[dimension])
        if dimension in named
        else observed_dimension(dimension)
        for dimension in DIMENSIONS
    ]


def preimage_payload(
    *,
    decision_id: str = DECISION_ID,
    decision_revision: int = 1,
    record_seal: str | None = None,
    projection_seal: str | None = None,
    host_id: str = HOST_ID,
    store_id: str = STORE_ID,
    epoch: str = EPOCH,
    agent_family: str = FAMILY,
) -> dict[str, Any]:
    """A preimage reference that reproduces from a real decision record by default.

    The seals are computed from an actual admitted record rather than stubbed, so
    a test that pairs this preimage with that record proves the binding rather than
    proving that two stubs agree. ``decision_revision`` above 1 links through the
    real revision-1 seal, exactly as HOK-243 requires.
    """
    identity: dict[str, Any] = {
        "host_id": host_id,
        "store_id": store_id,
        "epoch": epoch,
        "agent_family": agent_family,
    }
    initial = admit_strategic_decision(
        strategic_decision_payload(decision_id, revision=1, **identity)
    )
    record = initial
    for revision in range(2, decision_revision + 1):
        record = admit_strategic_decision(
            strategic_decision_payload(
                decision_id,
                revision=revision,
                supersedes_revision_seal=record.record_seal(),
                **identity,
            )
        )
    return {
        "decision_binding": {
            "host_id": host_id,
            "agent_family": agent_family,
            "store_id": store_id,
            "epoch": epoch,
        },
        "decision_id": decision_id,
        "decision_revision": decision_revision,
        "record_seal": record_seal if record_seal is not None else record.record_seal(),
        "projection_seal": projection_seal
        if projection_seal is not None
        else record.projection.projection_seal(),
    }


def reconciliation_payload(
    reconciliation_id: str = RECONCILIATION_ID,
    *,
    revision: int = 1,
    revision_kind: str = "INITIAL",
    revision_reason: str | None = None,
    supersedes_revision_seal: str | None = None,
    host_id: str = HOST_ID,
    store_id: str = STORE_ID,
    epoch: str = EPOCH,
    agent_family: str = FAMILY,
    preimage: dict[str, Any] | None = None,
    authorization_state: str = "AUTHORIZED_ELSEWHERE",
    authorization_reference: str | None = AUTHORITY_REFERENCE,
    execution_state: str = "EXECUTED",
    executed_direction_id: str | None = EXECUTED_DIRECTION_ID,
    observations: list[dict[str, Any]] | None = None,
    **overrides: Any,
) -> dict[str, Any]:
    """A complete, admissible reconciliation of the fixture decision.

    Defaults describe the ordinary case: an action authorised elsewhere, executed
    as ``direction-alpha``, with all five dimensions observed. Overrides replace
    top-level keys outright.
    """
    payload: dict[str, Any] = {
        "contract_version": "1.0.0",
        "reconciliation_id": reconciliation_id,
        "revision": revision,
        "revision_kind": revision_kind,
        "revision_reason": revision_reason,
        "supersedes_revision_seal": supersedes_revision_seal,
        "binding": {
            "host_id": host_id,
            "agent_family": agent_family,
            "store_id": store_id,
            "epoch": epoch,
        },
        "preimage": preimage if preimage is not None else preimage_payload(),
        "reconciled_at": RECONCILED_AT,
        "reconciled_by": RECONCILED_BY,
        "sensitivity": "NON_SENSITIVE",
        "authorization_state": authorization_state,
        "authorization_reference": authorization_reference,
        "execution_state": execution_state,
        "executed_direction_id": executed_direction_id,
        "observations": observations if observations is not None else observation_set(),
    }
    payload.update(overrides)
    return payload


@pytest.fixture
def journal_root(tmp_path: Path) -> Path:
    return tmp_path / "reconciliation-root"


@pytest.fixture
def journal(journal_root: Path, fixed_clock: Callable[[], str]) -> Iterator[ReconciliationJournal]:
    """An open reconciliation journal bound to the fixture host, family and epoch."""
    opened = ReconciliationJournal.create(
        journal_root,
        store_id=STORE_ID,
        host_id=HOST_ID,
        agent_family=AgentFamily.CLAUDE,
        epoch=EPOCH,
        clock=fixed_clock,
    )
    try:
        yield opened
    finally:
        opened.close()


@pytest.fixture
def fixture_decision() -> StrategicDecisionRecord:
    """The pre-action record the fixture reconciliation names. Never mutated."""
    return admit_strategic_decision(strategic_decision_payload())


def protocol_payload(**overrides: Any) -> dict[str, Any]:
    """A complete, valid pre-registration fixing all eight metric families."""
    payload: dict[str, Any] = {
        "contract_version": "1.0.0",
        "protocol_id": "lc-shadow-p1",
        "revision": 1,
        "epoch": EPOCH,
        "registered_at": "2026-08-14T09:00:00Z",
        "tasks": ["branch-direction-ranking", "abstention-calibration"],
        "splits": [
            {
                "split": "TRAIN",
                "corpus_seal": "sha256:train-corpus",
                "item_count": 400,
                "disjoint_from": ["VALIDATION", "HOLDOUT"],
            },
            {
                "split": "VALIDATION",
                "corpus_seal": "sha256:validation-corpus",
                "item_count": 100,
                "disjoint_from": ["TRAIN", "HOLDOUT"],
            },
            {
                "split": "HOLDOUT",
                "corpus_seal": "sha256:holdout-corpus",
                "item_count": 100,
                "disjoint_from": ["TRAIN", "VALIDATION"],
            },
        ],
        "baselines": [
            {
                "name": "always-abstain",
                "kind": "TRIVIAL",
                "description": "abstain on every branch point",
            },
            {
                "name": "propensity-argmax",
                "kind": "STRONG",
                "description": "pick the highest-propensity candidate",
            },
        ],
        "seeds": [11, 23, 37],
        "metrics": [
            {
                "name": "success-rate",
                "family": "SUCCESS",
                "direction": "HIGHER_IS_BETTER",
                "threshold": 0.6,
                "required": True,
            },
            {
                "name": "violation-rate",
                "family": "VIOLATION",
                "direction": "LOWER_IS_BETTER",
                "threshold": 0.05,
                "required": True,
            },
            {
                "name": "cost-per-episode",
                "family": "COST",
                "direction": "LOWER_IS_BETTER",
                "threshold": 2.0,
                "required": True,
            },
            {
                "name": "information-gain",
                "family": "INFORMATION",
                "direction": "HIGHER_IS_BETTER",
                "threshold": 0.1,
                "required": True,
            },
            {
                "name": "reversibility",
                "family": "REVERSIBILITY",
                "direction": "HIGHER_IS_BETTER",
                "threshold": 0.8,
                "required": True,
            },
            {
                "name": "calibration-error",
                "family": "CALIBRATION",
                "direction": "LOWER_IS_BETTER",
                "threshold": 0.1,
                "required": True,
            },
            {
                "name": "p99-regret",
                "family": "TAIL",
                "direction": "LOWER_IS_BETTER",
                "threshold": 3.0,
                "required": True,
            },
            {
                "name": "drift-divergence",
                "family": "DRIFT",
                "direction": "LOWER_IS_BETTER",
                "threshold": 0.2,
                "required": False,
            },
        ],
        "sensitivity_analyses": [
            "re-score with each seed dropped in turn",
            "re-score with the abstention threshold at 0.30 and 0.40",
        ],
        "failure_cases": [
            "candidate set of size one, where propensity carries no information",
            "outcome observability NONE for more than half the holdout",
        ],
    }
    payload.update(overrides)
    return payload


#: The corpus seal each split declares in :func:`protocol_payload`.
CORPUS_SEALS: dict[str, str] = {
    "TRAIN": "sha256:train-corpus",
    "VALIDATION": "sha256:validation-corpus",
    "HOLDOUT": "sha256:holdout-corpus",
}


def measurement_payload(
    protocol_seal: str,
    *,
    split: str = "VALIDATION",
    purpose: str = "EXPLORATION",
    epoch: str = EPOCH,
    values: dict[str, float] | None = None,
    seeds: tuple[int, ...] = (11, 23, 37),
    corpus_seal: str | None = None,
) -> dict[str, Any]:
    """Measurements for every required metric, on every pre-registered seed."""
    defaults = {
        "success-rate": 0.72,
        "violation-rate": 0.02,
        "cost-per-episode": 1.4,
        "information-gain": 0.31,
        "reversibility": 0.91,
        "calibration-error": 0.04,
        "p99-regret": 2.1,
    }
    if values is not None:
        defaults.update(values)
    return {
        "contract_version": "1.0.0",
        "protocol_seal": protocol_seal,
        "corpus_seal": corpus_seal if corpus_seal is not None else CORPUS_SEALS[split],
        "epoch": epoch,
        "purpose": purpose,
        "split": split,
        "measurements": [
            {"metric": metric, "split": split, "seed": seed, "value": value}
            for metric, value in sorted(defaults.items())
            for seed in seeds
        ],
    }


@pytest.fixture
def protocol() -> Preregistration:
    """A complete, valid pre-registration."""
    return load_preregistration(protocol_payload())


def build_measurements(payload: dict[str, Any]) -> MeasurementSet:
    return load_measurement_set(payload)


@pytest.fixture
def validation_measurements(protocol: Preregistration) -> MeasurementSet:
    """The raw validation evidence used by the validation verdict fixture."""
    return build_measurements(measurement_payload(protocol.protocol_seal()))


@pytest.fixture
def validation_verdict(
    protocol: Preregistration, validation_measurements: MeasurementSet
) -> Verdict:
    """A real, self-sealing CONTINUE verdict on the validation split."""
    return evaluate(protocol, validation_measurements)


@pytest.fixture
def holdout_measurements(protocol: Preregistration) -> MeasurementSet:
    """The raw final-holdout measurements from which the fixture verdict is derived."""
    return build_measurements(
        measurement_payload(protocol.protocol_seal(), split="HOLDOUT", purpose="FINAL_VERDICT")
    )


@pytest.fixture
def holdout_ledger(tmp_path: Path) -> HoldoutLedger:
    """The durable usage ledger carrying the fixture verdict's consumption receipt."""
    return HoldoutLedger(tmp_path / "holdout-fixture.json")


@pytest.fixture
def failing_holdout_measurements(protocol: Preregistration) -> MeasurementSet:
    """Raw holdout evidence whose required success metric fails."""
    return build_measurements(
        measurement_payload(
            protocol.protocol_seal(),
            split="HOLDOUT",
            purpose="FINAL_VERDICT",
            values={"success-rate": 0.41},
        )
    )


@pytest.fixture
def failing_holdout_verdict(
    protocol: Preregistration, failing_holdout_measurements: MeasurementSet
) -> Verdict:
    """A reproducible KILL verdict, scored without claiming a new holdout spend."""
    from latent_compass.protocol import score_measurements

    return score_measurements(protocol, failing_holdout_measurements)


@pytest.fixture
def holdout_verdict(
    protocol: Preregistration,
    holdout_measurements: MeasurementSet,
    holdout_ledger: HoldoutLedger,
) -> Verdict:
    """A real, self-sealing final CONTINUE verdict on the holdout."""
    return evaluate(
        protocol,
        holdout_measurements,
        holdout_ledger=holdout_ledger,
        consumed_at="2026-08-14T13:00:00Z",
    )


def reseal(verdict: Verdict, **changes: Any) -> Verdict:
    """Edit a verdict and re-seal it honestly, as a legitimate producer would."""
    edited = verdict.model_copy(update=changes)
    return edited.model_copy(update={"verdict_seal": recompute_verdict_seal(edited)})


@pytest.fixture
def store_root(tmp_path: Path) -> Path:
    return tmp_path / "ledger-root"


@pytest.fixture
def store(store_root: Path, fixed_clock: Callable[[], str]) -> Iterator[LedgerStore]:
    """An open store bound to the fixture host, family and epoch."""
    opened = LedgerStore.create(
        store_root,
        store_id=STORE_ID,
        host_id=HOST_ID,
        agent_family=AgentFamily.CLAUDE,
        epoch=EPOCH,
        clock=fixed_clock,
    )
    try:
        yield opened
    finally:
        opened.close()


def write_json(path: Path, payload: object) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")
    return path


def read_corpus_json(directory: Path, name: str) -> Any:
    return json.loads((directory / name).read_text(encoding="utf-8"))


@pytest.fixture
def benchmark_corpus_dir() -> Path:
    """The committed synthetic corpus, read-only."""
    return BENCHMARK_CORPUS


@pytest.fixture
def mutable_corpus(tmp_path: Path) -> Path:
    """A private copy of the committed corpus that a test may corrupt.

    Every hostile test works on a copy. A test that edited the committed corpus
    would pass once and then poison every later run in the same session.
    """
    destination = tmp_path / "corpus"
    shutil.copytree(BENCHMARK_CORPUS, destination)
    return destination


@pytest.fixture
def benchmark_manifest(benchmark_corpus_dir: Path) -> CorpusManifest:
    return load_corpus_manifest(read_corpus_json(benchmark_corpus_dir, "manifest.json"))


@pytest.fixture
def benchmark_protocol(benchmark_corpus_dir: Path) -> Preregistration:
    return load_preregistration(read_corpus_json(benchmark_corpus_dir, "protocol.json"))


@pytest.fixture
def benchmark_spec(benchmark_corpus_dir: Path) -> BenchmarkSpec:
    return load_benchmark_spec(read_corpus_json(benchmark_corpus_dir, "spec.json"))


def snapshot_tree(root: Path) -> dict[str, str]:
    """Content digest of every file under ``root``, keyed by relative path."""
    return {
        str(path.relative_to(root)).replace("\\", "/"): hashlib.sha256(
            path.read_bytes()
        ).hexdigest()
        for path in sorted(root.rglob("*"))
        if path.is_file()
    }
