"""latent-compass — a proof-governed latent direction arbiter for coding agents.

The operational surface **validates and records**. It takes advisories supplied
by a caller, refuses anything ambiguous or unversioned, and appends what survives
to a local, append-only, host-bound ledger. Separately, HOK-188 runs four closed
policies offline over recorded synthetic cases and computes diagnostic
confidences; the scoped summaries never reach an agent and are rejected when
passed directly as lifecycle evidence.

It is advisory by construction: it holds no execution, mutation, promotion or
final-decision authority, and the deterministic judge of truth, invariants,
impact, gates and proof stays outside this package entirely.

Start at :mod:`latent_compass.authority` — the boundary is the product.
"""

from __future__ import annotations

from latent_compass.authority import (
    RefusalReason,
    TransitionAuthorization,
    authority_boundary_seal,
    authority_boundary_snapshot,
    authorize_transition,
)
from latent_compass.benchmark import (
    BaselineId,
    BenchmarkReport,
    BenchmarkSpec,
    CorpusManifest,
    run_benchmark,
    verify_report,
)
from latent_compass.contracts import (
    AUTHORITY_CONTRACT_VERSION,
    BENCHMARK_CONTRACT_VERSION,
    DECISION_MEMORY_CONTRACT_VERSION,
    DECISION_MEMORY_FORMAT_VERSION,
    DECISION_TRANSFER_CONTRACT_VERSION,
    EPISODE_CONTRACT_VERSION,
    JUDGEABLE_PROJECTION_CONTRACT_VERSION,
    LEDGER_FORMAT_VERSION,
    PROSPECTIVE_COLLECTION_CONTRACT_VERSION,
    PROSPECTIVE_COLLECTION_FORMAT_VERSION,
    PROTOCOL_CONTRACT_VERSION,
    RECONCILIATION_CONTRACT_VERSION,
    RECONCILIATION_FORMAT_VERSION,
    RECONCILIATION_REPLAY_CONTRACT_VERSION,
)
from latent_compass.decision_memory import (
    ActiveDecision,
    DecisionBinding,
    DecisionImpactClass,
    DecisionMemoryStore,
    DecisionOriginKind,
    DecisionTransferEnvelope,
    SensitivityClassification,
    StrategicDecisionRecord,
    admission_limits,
    admit_strategic_decision,
    admit_transfer_envelope,
)
from latent_compass.decision_reconciliation import (
    AuthorizationState,
    DecisionPreimageReference,
    DimensionObservation,
    ExecutionState,
    ObservationStatus,
    ReconciliationJournal,
    ReconciliationRecord,
    ReconciliationReplay,
    UnknownReason,
    admit_reconciliation,
    reconciliation_limits,
    replay_reconciliation,
)
from latent_compass.episode import AgentFamily, Episode, load_episode
from latent_compass.errors import (
    AuthorityRefusal,
    ContractViolation,
    DecisionMemoryViolation,
    DecisionRevisionConflict,
    IntegrityError,
    LatentCompassError,
    LedgerError,
    PairwiseCaptureViolation,
    PreimageMismatch,
    ProspectiveCollectionViolation,
    ProtocolViolation,
    ReconciliationRevisionConflict,
    ReconciliationViolation,
    SensitiveContentRefused,
    TransferRefused,
    UnsupportedContractVersion,
)
from latent_compass.governance import DeletionMode, Tombstone
from latent_compass.ledger import LedgerStore
from latent_compass.pairwise_capture import (
    JudgeableDecisionProjection,
    PairwiseJudgeInput,
    load_judgeable_projection,
    load_pairwise_judge_input,
    verify_pairwise_judge_input,
)
from latent_compass.prospective_collection import (
    AbortReason,
    CaseState,
    ExactBinomialInputs,
    ExactBinomialResult,
    HardExclusion,
    PlanState,
    PowerStatus,
    ProspectiveCollectionJournal,
    ProspectiveCollectionPlan,
    StopCondition,
    admit_prospective_plan,
    plan_exact_one_sided_binomial,
)
from latent_compass.protocol import (
    HoldoutLedger,
    Preregistration,
    Verdict,
    evaluate,
    load_measurement_set,
    load_preregistration,
    recompute_verdict_seal,
)
from latent_compass.vocabulary import (
    Actor,
    Advisory,
    AdvisoryKind,
    Capability,
    ContinueKill,
    LifecycleState,
    may_issue_direction,
)

__version__ = "0.1.0"

__all__ = [
    "AUTHORITY_CONTRACT_VERSION",
    "BENCHMARK_CONTRACT_VERSION",
    "DECISION_MEMORY_CONTRACT_VERSION",
    "DECISION_MEMORY_FORMAT_VERSION",
    "DECISION_TRANSFER_CONTRACT_VERSION",
    "EPISODE_CONTRACT_VERSION",
    "JUDGEABLE_PROJECTION_CONTRACT_VERSION",
    "LEDGER_FORMAT_VERSION",
    "PROSPECTIVE_COLLECTION_CONTRACT_VERSION",
    "PROSPECTIVE_COLLECTION_FORMAT_VERSION",
    "PROTOCOL_CONTRACT_VERSION",
    "RECONCILIATION_CONTRACT_VERSION",
    "RECONCILIATION_FORMAT_VERSION",
    "RECONCILIATION_REPLAY_CONTRACT_VERSION",
    "AbortReason",
    "ActiveDecision",
    "Actor",
    "Advisory",
    "AdvisoryKind",
    "AgentFamily",
    "AuthorityRefusal",
    "AuthorizationState",
    "BaselineId",
    "BenchmarkReport",
    "BenchmarkSpec",
    "Capability",
    "CaseState",
    "ContinueKill",
    "ContractViolation",
    "CorpusManifest",
    "DecisionBinding",
    "DecisionImpactClass",
    "DecisionMemoryStore",
    "DecisionMemoryViolation",
    "DecisionOriginKind",
    "DecisionPreimageReference",
    "DecisionRevisionConflict",
    "DecisionTransferEnvelope",
    "DeletionMode",
    "DimensionObservation",
    "Episode",
    "ExactBinomialInputs",
    "ExactBinomialResult",
    "ExecutionState",
    "HardExclusion",
    "HoldoutLedger",
    "IntegrityError",
    "JudgeableDecisionProjection",
    "LatentCompassError",
    "LedgerError",
    "LedgerStore",
    "LifecycleState",
    "ObservationStatus",
    "PairwiseCaptureViolation",
    "PairwiseJudgeInput",
    "PlanState",
    "PowerStatus",
    "PreimageMismatch",
    "Preregistration",
    "ProspectiveCollectionJournal",
    "ProspectiveCollectionPlan",
    "ProspectiveCollectionViolation",
    "ProtocolViolation",
    "ReconciliationJournal",
    "ReconciliationRecord",
    "ReconciliationReplay",
    "ReconciliationRevisionConflict",
    "ReconciliationViolation",
    "RefusalReason",
    "SensitiveContentRefused",
    "SensitivityClassification",
    "StopCondition",
    "StrategicDecisionRecord",
    "Tombstone",
    "TransferRefused",
    "TransitionAuthorization",
    "UnknownReason",
    "UnsupportedContractVersion",
    "Verdict",
    "__version__",
    "admission_limits",
    "admit_prospective_plan",
    "admit_reconciliation",
    "admit_strategic_decision",
    "admit_transfer_envelope",
    "authority_boundary_seal",
    "authority_boundary_snapshot",
    "authorize_transition",
    "evaluate",
    "load_episode",
    "load_judgeable_projection",
    "load_measurement_set",
    "load_pairwise_judge_input",
    "load_preregistration",
    "may_issue_direction",
    "plan_exact_one_sided_binomial",
    "recompute_verdict_seal",
    "reconciliation_limits",
    "replay_reconciliation",
    "run_benchmark",
    "verify_pairwise_judge_input",
    "verify_report",
]
